version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
   image: docker.io/bitnami/kafka:3.4.1
   container_name: kafka
   ports:
     - "9094:9094"
   environment:
     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
     - ALLOW_PLAINTEXT_LISTENER='yes'
   depends_on:
     - zookeeper 

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      -./postgres/init.sql:/docker-entrypoint.initdb.d/init.sql


  fake_data:
    container_name: fake_data
    build:
      context: ./fake_data/
    command: python /opt/fake_data/gen_fake_data.py
    restart: on-failure
    depends_on:
      - postgres
      - kafka

  

